### ISSUE TITLE
[Deployment] Improve the Travis deployment script for workers

### ISSUE THREAD

**Issue by zwliew** [opengovsg/postmangovsg#1049]
**Is your feature request related to a problem? Please describe.**

There are 2 issues with the Travis deploy script for workers:
1. The exit code for the script depends solely on the exit code for the logger deployment. This masks potential errors in intermediate steps of the scripts.
2. The logger and sender deployments are run sequentially. This is potentially slower.

**Describe the solution you'd like**
1. Return a non-zero exit code if any of the intermediate steps fail.
2. Run the deployments concurrently. (could test to see whether this actually reduces deployment time)

**Comment by lamkeewei** [comment]
I seems (need verification) that think when `docker build` fails, the script continues. This result in an error later on as the container image never gets pushed.

**Comment by zwliew** [comment]
I see. I guess a better goal for point 1 would then be to return a non-zero exit code if any of the steps fail.

**Comment by lamkeewei** [comment]
> I see. I guess a better goal for point 1 would then be to return a non-zero exit code if any of the intermediary steps fail.

Yep. Agree. What happened for release yesterday was that Docker pull request was hit on Travis, which resulted in the container not being built and pushed. However, the script continued to create a new task definition on ECS with the unpushed Docker image. The deploy obviously failed eventually because the ECS tasks cannot start with non-existent Docker image.
