### ISSUE TITLE
Allow users to customize sender name

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1174]
**Aim**
to improve email legitimacy. A key reason why recipients perceive Postman's emails as suspicious is because the sender name is Postman whereas the email supposedly was sent by an agency.

**Todo**
- users should be able to customise the sender name
- "via Government Mail" should be appended to the end of the sender name regardless, and this should be communicated to the user. this is because savvy users will also realise and are trained to ensure that the sender name matches the domain.

**Comment by viviennechong** [comment]
Hi!

**Comment by viviennechong** [comment]
Hi Kee Wei,

While doing the login screens for another project, I realised that we should put in examples (like "e.g. MOH Appointment") in the in-field labels instead of just "Enter sender name". This would make it more intuitive for new/unfamiliar users as they would be able to get a sense of what is a meaningful sender name to put in the email.

## Changes to the labels
### From
- "Enter sender name" --> "e.g. MOH Appointment"

### Email Subject
- "Enter email subject" --> "e.g. Appointment Confirmation"

### Inbox for replies
- "Enter reply-to email address" --> "e.g. user@agency.gov.sg"

The message label is unchanged.

## Updated screens
I've marked out the changes with arrows.
![NonCustom](https://user-images.githubusercontent.com/83941894/118433244-1a61b180-b70d-11eb-906b-fbed72cf7bed.png)

![NonCustom-ErrorMessage](https://user-images.githubusercontent.com/83941894/118433281-349b8f80-b70d-11eb-801d-993166ad5451.png)

![Custom](https://user-images.githubusercontent.com/83941894/118433295-3bc29d80-b70d-11eb-8786-c55287e4f627.png)

Thanks!

**Comment by lamkeewei** [comment]
@viviennechong also answering your question in the screenshot, yep `user@agency.gov.sg` is a placeholder value. Changes requested are also updated at #1193. Feel free to leave other changes you want there.

**Comment by syan-syan** [comment]
@lamkeewei @viviennechong lets use the placeholder 'Ministry of Health' instead of MOH Appointment for sender name. the rest are ok. thanks!
