### ISSUE TITLE
Restructure agency collection to support agency logos

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1203]
probably need 3 keys: email domain, agency name and agency logo maybe a short name like formsg?

**Comment by jeantanzj** [comment]
I'm not sure how we are hosting the logo. 
If we are using CID - we probably want to store the logo on disk so that we can load it into a buffer for attachment. Then the logo_uri would point to a location on disk. 
If we are using a file path (eg our own s3 bucket), then logo_uri should be a *relative* file path.
If we are using file.go.gov.sg, then logo_uri would be an *absolute* link to the file.

**Comment by syan-syan** [comment]
ok to use CID since file size is small

**Comment by mjgui** [comment]
Will do this with the PR for email templates

**Comment by mjgui** [comment]
Currently, `agencies` table has a single column `domain`, with two possible formats:
- `.gov.sg` (wildcard), or 
- `@moe.edu.sg` (specific domain)

**Proposed Solution**

- `agencies` table will have 3 columns, `domain` (pri key), `name` and `logo_uri`
- `users` table will have new column `agency_domain` as foreign key on `agencies` table
- agency domain will be filled in with a `BeforeCreate` hook
- `agencies` table needs to be populated (manually) with all known agencies `@__.gov.sg`, 
- each `domain` will have a single row with assoicated name and logo

**Possible Issues**

- Fetching the agency/logo for a particular campaign requires either 3 queries, or a join across 3 tables (`email_templates` to `users` to `agencies`)
  - Unlikely to be that expensive since lookup is via primary key and user/agency tables are relatively small
- Currently, some users authenticate email with wildcard domain (`*@*.gov.sg`) that is not in the `agencies` table
  - Have a fallback row in `agencies` as default value for foreign key (e.g. all unrecognized gov.sg domains will point to generic gov.sg entry)
  - Might have to manually handle non gov.sg emails
  - If we choose to retroactively support a new domain, we need to backpatch all users of a particular domain to the new `agencies` entry
- There might be repetition between entries in `agencies` (e.g. `@open.gov.sg` and `@postman.gov.sg` are different rows but both have the same logo and name, Open Gov Products), resulting in potential inconsistencies in logo/name spelling
  - Might not be a significant problem since the list of domains is not very large

**Comment by mjgui** [comment]
Closing this for now

**Potential extensions:**
- [ ] Having a "display name" when it needs to be displayed in a paragraph (e.g. "Supreme Court" vs "the Supreme Court")
