### ISSUE TITLE
UI/UX fixes for Custom Sender Name

### ISSUE THREAD

**Issue by sarahsalim** [opengovsg/postmangovsg#1218]
Amendments for Custom Sender Name:

1. Remove 'Postman.gov.sg' in the text field. 
**Why:** User should see the placeholder and via append immediately to understand the feature more intuitively. We also want to discourage the use of 'Postman.gov.sg' cause that's the issue we're trying to solve.
<img width="721" alt="Screenshot 2021-06-02 at 12 52 06 PM" src="https://user-images.githubusercontent.com/27407507/120427997-7e3ed800-c3a5-11eb-8767-e21b19d493a7.png">

2. Remove full stop for 'Sender details'. Generally, when an instruction or description is composed of a single sentence, we do not include a period at the end of the sentence. When there is more than one sentence, all sentences should have a period. Can read more about it's practised for this team [here](https://docs.appian.com/suite/help/19.2/ux_formatting_and_punctuation.html#:~:text=Period%20Usage,sentences%20should%20have%20a%20period.)

3. For all mentions of 'e.g.' - make them lowercase. Meaning capital 'E' should change to lowercase 'e'
<img width="586" alt="Screenshot 2021-06-02 at 1 36 03 PM" src="https://user-images.githubusercontent.com/27407507/120429366-dbd42400-c3a7-11eb-8319-22c0de1cb708.png">

4. Description changes:
**Subject**
Keep it short, specific and personalised. Try to use less than 10 words.

5. Change default sender email to 'donotreply@postman.gov.sg' as discussed

**Comment by lamkeewei** [comment]
@sarahsalim @viviennechong if the user has a custom from address, should the sender name be prepopulated to what they have configured?

**Comment by syan-syan** [comment]
@lamkeewei I think no need to create this edge case as it would be annoying to keep pre-populating the same value if they want a different sender name in the future. shouldn't make them remember two sets of behaviour. and if we only pre-populate once - there's not that much value for the additional complexity.

**Comment by viviennechong** [comment]
Hi Kee Wei!

As discussed yesterday, users without a custom email address domain will not see the email address field.

Was wondering if we could also vary the description to say **"Sender name" instead of "Sender details" for this case**? This is to reduce the risk of users entering an email address instead of a sender name

In summary,
### **Users with no custom email address will see this:**
- Description: Sender name
- No email address field

![image](https://user-images.githubusercontent.com/83941894/123279075-190c7b80-d53a-11eb-8f00-ed7477d27714.png)

### **Users with a custom email address will see this:**
- Description: Sender details
- Email address field is shown

![image](https://user-images.githubusercontent.com/83941894/123278638-af8c6d00-d539-11eb-8ba7-5ed2ff43c822.png)

Thanks :))

**Comment by syan-syan** [comment]
@lamkeewei @viviennechong to reduce complexity, lets just have "Sender name and email address" for all cases!
