### ISSUE TITLE
Research unsub flow

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1415]
**Is your feature request related to a problem? Please describe.**

Current unsub link does not do anything. Postman receives emails from citizens to inform us that they do not wish to receive certain messages from particular agencies. This is likely a result of too many promotional/marketing messages being sent out through postman. Ideally, we don't want any of such messages being sent from postman, we want to reduce the number of non-essential messages.

**Should we fix unsub button?** The concept of unsub comes from subscription. Since postman doesn't want to be a marketing mailer tool, our goal is to remove the need to unsubscribe and only send out messages that the citizen should receive. 

Additional concerns and problems:
- Agencies can't view who they sent previous campaigns to and what email content they sent
- Agencies does not have a birds eye view of the general relevancy of the email that they sent (e.g total not relevant email)

**Describe the solution you'd like**
Our goals are:
- Have a way to citizens to indicate that they want to stop receiving non-relevant emails into their mailbox
- Inform agencies that citizens do not want to receive such emails (currently done through weekly digest email, can explore adding it on campaign report page to show rate of non-relevancy)
- Have a way to penalise agencies who has high non-relevancy rate

1. **Getting citizen feedback**
One way we can do this is to introduce the concept of "Not relevant" link. This gives recipients opportunity to let us know that a particular email is not relevant to them. Asking them why helps us understand why this is not useful, instead of just blindly unsubscribing them to the mailers.

2. **Share feedback with admin users**
Inform agencies that recipients do not want to receive such emails (currently done through weekly digest email, can explore adding it on campaign report page to show rate of non-relevancy)

3. **Enforcement** 
We want to ensure that agencies do something about this, we should disincentivise agencies for not actively cleaning up their contact list and include people who did not choose to receive these messages.

**Describe alternatives you've considered**
When citizen X clicks on not relevant button, agency owner will receive an email notif from postman that this particular user has confirmed that this email (with their email title appended in this notification email to help identify offending email) is not relevant to them. 

TBC - how to stop them from sending to the same user from Postman's end? Mailchimp also has a way to suspend accounts who has too high unsub rate (reference below)

**Additional context**
https://www.imda.gov.sg/for-community/Infocomm-regulation-and-guides/unsolicited-communications/best-practices-for-organisations
https://mailchimp.com/help/about-unsubscribes/

**Comment by pirsquare** [comment]
Hi there, I run email marketing platform similar to Mailchimp. Honestly think this be a core feature in the first place because I'm getting tons of emails from various govt agencies or their partners asking me do surveys. None of them have any form of unsub link. 

With current status quo, recipients can only stop getting these emails by.
- Informing sender manually that they wish to unsub (Too tedious and too much work)
- Blocking the sender email (Not good because they won't get important transactional emails from agency)
- Mark email as spam (If you don't allow users to unsub, you shouldn't be surprise by them marking emails as spam. This can have adverse effect because even a 0.1% marked spam rate will impact deliverability)

To implement this, you just need to maintain a suppression list. You can even do this for sms or other channels.
- So when a user unsubs, you simply add a record to indicate they've unsub from email communications for a specific agency/account.
- When agency broadcast future emails, you automatically exclude the unsubscribers. We use "Skip" status to indicate this.
- There's no additional work on agency end. Of course, they should be able to view, access and download the suppression list on their end.

**Comment by lisatjide** [comment]
Hi @pirsquare, thank you for your feedback and suggestions! We will take note of this as we look into the unsub bahviour of our users.

**Comment by lisatjide** [comment]
closing this since we have implemented unsub flow with a the modal to collect reason why someone unsubbed
