### ISSUE TITLE
Logging and alarms for twilio failures

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1455]
Currently we do not track errors on twilio and we do not have a baseline errors to know when something is not right. 
We should not be taking user's numbers as baseline as some of these numbers are not working and the errors may not be accurate.

- [ ] Check Budget (estimate how much we're going to spend)

**Comment by stanleynguyen** [comment]
A rough cost proposal (that's within our budget) for this with a setup of 1 mobile number and 10 min frequency:
- 1 SG number with SMS capability: SGD75/month
- Cost to send out test messages: 24 * 6 * .0395 * 30 = SGD170/month

Rounding up to account for misc cost for datadog alerts we will incur SGD250 monthly

**Comment by stanleynguyen** [comment]
Implementation details:

For code:
- [ ] we will have a `setInterval` in our healthcheck service to send out a message (using our Postman Twilio credentials) to the 2 recipient numbers (also on Postman twilio) every 20 minutes
- [ ] We need to create an endpoint to specifically to handle the callbacks for recipient numbers (i.e. we get a callback when messages arrive)
- [ ] We need to create a new redis client (add to our existing redis service module) that connect to a new redis database (in the same existing cluster) to store the count of successful messages
- [ ] On server bootup (i.e. when the redis client first connect), set `healthcheck_sms_success` to 2
- [ ] Upon receiving the callbacks, we will:
  - [ ] Set the entry of successful message to 1 if `healthcheck_sms_success` is non-existent on the db
  - [ ] Set the entry to entry + 1 if it already exists
- [ ] modify our healthcheck endpoint to return a JSON object instead, something like `{ "message": "OK"}`. Inside the endpoint handler, we will check for `healthcheck_sms_success` value, the `message` would be `"Twilio down"` (still return with 200 status code => will explain this later) if the value is not there or less than 2

=> This setup is so that we can have 2 different healthcheck on betteruptime.com for our Postman service:
- One is for general service health (will only alert and show red on our https://status.postman.gov.sg/ if status is != 200)
- The other is for Twilio down and meant for internal usage only (will only alert when `Contains keyword "Twilio down"`

(The 2 above bullet points are how we want to set up our monitor on betteruptime.com)

**Comment by stanleynguyen** [comment]
Reassigning to @gweiying as your first task.
Please refer to the previous message for implementation details. I'll give u relevant accesses on Thurs during our onboard sess
