### ISSUE TITLE
update cost per SMS on SMS message editor

### ISSUE THREAD

**Issue by lisatjide** [opengovsg/postmangovsg#1579]
**Describe the bug**
Current pricing shown on editor is SGD 0.0395 but the pricing stated on Twilio's pricing page is in USD
<img width="896" alt="Screenshot 2022-06-10 at 3 29 28 PM" src="https://user-images.githubusercontent.com/23736580/173013638-b120cb16-b979-4cb5-9ca0-49386134ef2d.png">
<img width="661" alt="Screenshot 2022-06-10 at 3 25 03 PM" src="https://user-images.githubusercontent.com/23736580/173013863-51aa5310-f8bd-482d-803e-91071ad612e0.png">

However on our SMS message editor, it is currently SGD 0.0395.

**How to fix**
The accurate pricing on Postman editor should be 1.4*0.0395=0.0553. 
We can set the default exchange rate of 1USD=1.4SGD for now.

**Comment by tan-zx** [comment]
will work on this! instead of hard-coding the price ($0.0395), thinking of fetching it from Twilio's API instead (found [this](https://www.twilio.com/docs/sms/api/pricing#messagingcountry-pricing-properties)) 

will use the default exchange rate and change the text to let user know the approximate exchange rate used! (haha thought about fetching the exchange rate via API but I think that's unnecessary complexity)
