### ISSUE TITLE
Uncaught error if from address is not verified for transactional email endpoint

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/postmangovsg#1837]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/3666479/194825726-32e03a3b-3a9a-4eb1-955a-8642f42a4d96.png">

**Comment by tan-zx** [comment]
We actually noticed and discussed this earlier (see [here](https://github.com/opengovsg/postmangovsg/pull/1778#issuecomment-1264544947)) and @stanleynguyen is in the process of building out an endpoint for verifying from address (see [here](https://opengovproducts.slack.com/archives/CT8D1FESY/p1665651696739409))

Actually, I was typing this, I realize a simple way would be to check out `email_from_address` table (rather than actually run the check with AWS SES 🤔)
