### ISSUE TITLE
File name is inconsistent after uploading a file containing invalid recipients

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#268]
The file name displayed on campaign page is inconsistent when uploading an invalid file, after a valid file. 

**Expected behavior:**
Given an existing valid file with name `A.csv`, if we upload an invalid file `B.csv`, we expect the message logs to still contain the messages from `A.csv`, and the displayed filename to be `A.csv`.

**Actual behavior:**
Given an existing valid file with name `A.csv`, if we upload an invalid file `B.csv`, the message logs correctly contain the messages from `A.csv`, but the displayed filename is now `B.csv`.

**To reproduce:** 
For an sms campaign,
1) Upload a file with valid sms recipients with the file name: "sms-1.csv"
<img width="744" alt="Screenshot 2020-05-19 at 3 43 37 PM" src="https://user-images.githubusercontent.com/33819199/82299160-c0d68200-99e7-11ea-8c5a-4819cc98c525.png">
2) Upload a file with invalid recipients with the file name: "emails-5.csv"
<img width="830" alt="Screenshot 2020-05-19 at 3 43 58 PM" src="https://user-images.githubusercontent.com/33819199/82299146-bcaa6480-99e7-11ea-99cd-9f4d3f7274c5.png">
3) On refresh, campaign shows file name "emails-5.csv" even though the file was invalid (and the actual messages stored in the table are still from "sms-1.csv")
<img width="722" alt="Screenshot 2020-05-19 at 3 44 14 PM" src="https://user-images.githubusercontent.com/33819199/82299126-b7e5b080-99e7-11ea-90eb-cb437b37f5ed.png">

The same bug also occurs for email campaigns.

**Comment by lshaowei18** [comment]
Seems like its not just the file name that is affected. 

When an invalid file is uploaded, it replaces the valid file in s3 bucket but doesn't replace the params in the `sms_messages` table since it is unable to parse the invalid file.

I could still try to send but I would receive a 400 because the `valid` column for the campaign is set to false. We set `valid` to false every time we try to upload a file and only set it to true when the upload and hydration is successful. 

<img width="1680" alt="Screenshot 2020-05-26 at 8 19 35 AM" src="https://user-images.githubusercontent.com/33112945/82849256-a7729000-9f29-11ea-8949-4527c8985d02.png">

**Comment by lshaowei18** [comment]
The ideal user experience would be: 

1) User uploads valid file, message and campaign tables are updated.
2) User uploads invalid file, message and campaign tables are not updated.
3) When user refresh, file name should still be the valid file.

This would require some refactoring. Ideally we should wrap updating s3 bucket and message logs in a transaction.
