### ISSUE TITLE
Add package for interpolating the copywriting on frontend 

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#288]
**Is your feature request related to a problem? Please describe.**
Someone who wants to deploy Postman will have to dive into particular parts of the code base to change the copywriting. 

**Describe the solution you'd like**
I want to add an internationalization package (eg. https://lingui.js.org/tutorials/react.html) for others to change the text easily without diving into code.

**Comment by xming13** [comment]
Hi @jeantanzj / @pettypychen, I am keen to contribute to this issue. I have read the [contributing doc](https://github.com/opengovsg/postmangovsg/blob/develop/docs/CONTRIBUTING.md) and would like to check if contributions to this issue are welcomed and if anyone has started working on this.

If it is ok to proceed, I will be using https://lingui.js.org/tutorials/react.html library and set up a proof-of-concept with some of the key copywriting in the frontend first.
Otherwise, let me know if there are other issues that are opened for contributions. Thanks!

**Comment by jeantanzj** [comment]
Sure. Right now we're passing the copywriting through environment variables, so this would be very useful.
