### ISSUE TITLE
Load campaigns page by page on dashboard

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#317]
**Is your feature request related to a problem? Please describe.**
We already support offset and limit in the  `GET /campaigns` endpoint. But it's not used on frontend. Instead, we retrieve the entire list of campaigns

**Describe the solution you'd like**
Load campaigns using pagination on frontend

**Comment by lamkeewei** [comment]
In order to implement this, `/campaigns` will need to return the total number of campaigns for the frontend pagination component in order to calculate `pageCount` for `ReactPaginate`. 

I'm suggesting to add an additional field (`total_count`) to the JSON response to facilitate this: 
```json
{
  "campaigns":[
    {
      "id": 0,
      "name": "string",
      "created_at": "2020-06-02T09:04:16.173Z",
      "has_credential": true,
      "valid": true,
      "type": "SMS",
      "job_queue": [
        {
          "status": "READY",
          "sent_at": "2020-06-02T09:04:16.173Z"
        }
      ]
    }
  ],
  "total_count": 1
}
```

Let me know if this is ok @jeantanzj or if there's other preferred ways to do this. Thanks!
