### ISSUE TITLE
[Registered] Csv transform service

### ISSUE THREAD

**Issue by pregnantboy** [opengovsg/postmangovsg#364]
- parses csv
- imports templating module and hydrates rows
- encrypts hydrated messages with password
- generates password hash
- output csv should only contain `recipient`, `encrypted_payload` and `password_hash` columns
- upload stream to s3

**explore using workers, `papaparse` supports this out of the box**

**Comment by jeantanzj** [comment]
Can we look into sharing CSV parsing code with backend? Backend currently using csv-parse.

**Comment by jeantanzj** [comment]
Will look into parsing row by row and streaming the upload. Will stub the encryption service in this PR if not available yet

**Comment by lshaowei18** [comment]
@lamkeewei mentioned that frontend is using `papaparse` to parse the csv. Will start looking into it while the templating module PR is being reviewed.

**Comment by lshaowei18** [comment]
> @lamkeewei mentioned that frontend is using `papaparse` to parse the csv. Will start looking into it while the templating module PR is being reviewed.

During a sync up on 22 June we have decided that we will not include the parsing of csv into templating module PR and would refactor later down the line after the PR is merged. Related to #432.

**Comment by lshaowei18** [comment]
Password management is quite scary to me so I have been reading a little about how to store passwords. It seems to me like a sufficient approach would be to generate a random salt for each password and hashing the password with the random salt. When a user logins, we can take the password and hash it with the random salt that is generated and stored as part of the password hash and verify if the provided password is valid.

Google recommends a multi layered strategy: 
`Have the client computer hash the password using a cryptographically secure algorithm and a
unique salt provided by the server. When the password is received by the server, hash it again with a different salt that is unknown to the client. Be sure to store both salts securely.`

Does seem like they just use two salts instead of a random salt for each user.

I am still learning and trying to understand more about this, so if I am wrong please correct me!

**Comment by lshaowei18** [comment]
Started to look into the parsing of csv and here are my assumptions: 

- Reason why we want to stream the file is because we are afraid that the file is too big for us to store it in the browser
- We will parse the whole CSV file, and then loop through each row to template it.
- Loops through the templated messages and encrypt it

If that's the case, I think we can share the `parseCsv` between backend and frontend. 

Initially, I thought we will template it while parsing.

**Comment by lshaowei18** [comment]
So I have prototyped and here's a general view of what I envision this service to do:

- User creates a password protected email campaign
- User fills in the email subject and body, clicks on upload file
<img width="1680" alt="Screenshot 2020-06-29 at 10 59 40 AM" src="https://user-images.githubusercontent.com/33112945/85968430-b0a6bf00-b9f7-11ea-9bd6-13298dd5dd82.png">
- Once it is successfully uploaded, the following steps will run in the browser:

1) Get template body and subject from backend
2) If file size is more than 10mb (thinking if it should be 5mb), we will use multipart upload, if not we will just upload normally. (I have not tested this logic yet)

Multipart upload:
1) We will parse the csv files in chunks. The default chunk size is 10mb.
2) Initiate multipart upload by calling the backend, `/campaign/${campaignId}/upload/start-multipart`
3) For the first chunk, the column headers will be added to the top. `recipient,encrypted_payload,password_hash`
4) We need to verify that the column headers consist of recipient and password, as well as the required params from the template. I have not figured out how to do this yet.
5) For each chunk, each rows will be transformed into `${recipient},"${encryptedPayload}","${passwordHash}"`.
To get the encrypted payload, we need to first hydrate the template with the params from the row, and then encrypt the hydrated message with the password param. For password hash, we hash the password param with `bcrypt.hash`, 10 rounds. 
6) Once each row is transformed, we join all the transformed rows into a single string, separated by `\n`.
7) Each chunk will then call the backend to retrieve a presigned url. `/campaign/${campaignId}/upload/multipart`
8) Once the whole file is parsed, we will call the backend to complete the multi part upload. `/campaign/${campaignId}/upload/complete-multipart`
9) Upload considered done.

Single upload:
Have not tried this yet, my assumption is that it should be less complex.

### Why can't we just use multipart upload?
Multipart upload requires each part upload to be at least 5mb. In the event that our payload adds up to less than 5mb, we can't use multipart upload.

### Password hashing takes alot of time
I haven't timed this yet, but hashing 175k rows took about 15-30mins. Hydrating and encryption is relatively fast.

### Error handling
So the other time i think we agreed that we should complete the upload before handling the errors. However, there are still cases where the error will prevent the upload. Here are few that i can think of:

- Parsing error. There is something wrong with the csv file, and papaparse is unable to carry on with the parsing.
- Multipart upload. I think there are multiple things that can go wrong with multipart upload; CORS in browser preventing requests to be made to s3, failing to complete multipart upload because etag is wrong etc. 

In the event of such errors, how should we handle the situation?

### CORS in browsers
I don't quite understand the issue, but using default browsers like firefox and chrome, I can't make a get request to the s3 bucket `postmangovsg-dev-upload` due to the CORS in s3 being set as `*`. I might be wrong. Currently disabling web security on chrome when i work on this. `open -n -a Google\ Chrome --args --disable-web-security --user-data-dir=/tmp/chrome`

### UI/UX concerns
With the browser taking up a lot of time especially for the password hashing, the UI/UX will have to convey enough instruction to ensure that the user doesn't leave the page or refresh. Currently our UI/UX doesn't support this. (When i was testing, sometimes i can't tell if my browser is working hard or it crashed) 

## Papa parse, workers and async parsing
