### ISSUE TITLE
[Telegram] Link to add Telegram token

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#491]
**Is your feature request related to a problem? Please describe.**
<img width="864" alt="Screenshot 2020-07-06 at 4 50 13 PM" src="https://user-images.githubusercontent.com/39106042/86579500-ff33fa80-bfaf-11ea-9d9b-b2b1c051964f.png">

The link is currently linked to our guide. We received feedback that this was not the expected flow.

**Describe the solution you'd like**
The link should link to the modal to add in Telegram token under settings to improve the UX.

**Comment by lamkeewei** [comment]
Spoke to Sarah on this. The expected behaviour should be as follow: 
1. Link the user directly to the add Telegram credential modal upon clicking the link
2. After user has successfully completed the add credential flow, we will redirect them back to the create campaign modal with the state that they left it in (E.g. with campaign name filled in)

In addition, we will also add a help link on the add credential modal to link user to the guide if they are unsure on how to get a bot token.
