### ISSUE TITLE
Add computeChecksums to uploads to s3

### ISSUE THREAD

**Issue by jeantanzj** [opengovsg/postmangovsg#715]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
computeChecksums (Boolean) — whether to compute checksums for payload bodies when the service accepts it (currently supported in S3 only)

We need to verify the integrity of file when they're uploaded

**Comment by lamkeewei** [comment]
On closer look, I think setting `computeChecksums` might not help since uploading to S3 is done on the frontend. We don't use the `aws-sdk` on the frontend, so I'll manually calculate the file's MD5 checksum and set the `Content-MD5` header in the axios PUT request. 

For the backend, I'll check if `computeChecksums` work when downloading the object from S3. Otherwise, will look at other ways we can check the integrity of the download.
