### ISSUE TITLE
Add instructions for deduplicating in excel

### ISSUE THREAD

**Issue by pettypychen** [opengovsg/postmangovsg#737]
We have decided to remove the deduplication feature in the frontend. We need to optimise the UX by adding a sentence to redirect users to our guide if they need help figuring out how to do deduplication in excel. 

**Link to guide**: https://guide.postman.gov.sg/quick-start#remove-duplicates-in-excel

<img width="839" alt="Screenshot 2020-09-23 at 3 07 14 PM" src="https://user-images.githubusercontent.com/39106042/93978651-dd783180-fdae-11ea-97f3-d76d0da49c2b.png">

**Comment by NatMaeTan** [comment]
<img width="332" alt="Screenshot 2020-11-28 at 8 22 26 PM" src="https://user-images.githubusercontent.com/63220614/100565870-7bccca00-32ff-11eb-81d8-2fcbec11d4c7.png">


It will be good to use the Warning Notification from the design system here, instead of just plain text!

[Figma](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/%F0%9F%91%91Design-Master?node-id=5426%3A24150)
